# Generated by Django 5.2.17 on 2026-10-02 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=2048)),
                ("reading_minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("ready", "Ready"), ("failed", "Failed")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255)),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, related_name="links", to="links.tag")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_tag_per_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="link",
            index=models.Index(fields=["owner", "-created_at"], name="link_owner_recent_idx"),
        ),
        migrations.AddConstraint(
            model_name="link",
            constraint=models.UniqueConstraint(
                fields=("owner", "url"), name="unique_link_per_owner"
            ),
        ),
    ]
